# This tells Nixpacks to use the specified packages during the build process.
# Using a specific version of postgresql (e.g., postgresql_15) is more reliable
# as it includes all the necessary development headers.
[phases.setup]
nixPkgs = ["python3", "postgresql_15"]

# The start command to run after the build is complete.
[start]
cmd = "./wait-for-db.sh ${PGHOST} python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn smart_ticket.wsgi:application"
