# This file tells Nixpacks to set up the build environment.
# We no longer need to install postgresql or gcc because we're using
# the pre-compiled psycopg2-binary package.
[phases.setup]
nixPkgs = ["python3"]

# The start command to run after the build is complete.
[start]
cmd = "./wait-for-db.sh ${PGHOST} python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn smart_ticket.wsgi:application"
