# Generated by Django 5.2.4 on 2025-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_resolution_due_at_ticket_response_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('awaiting_customer_response', 'Awaiting Customer Response'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
